@baseUrl = http://localhost:3000/api/users

###
GET {{baseUrl}} HTTP/1.1

###
POST {{baseUrl}} HTTP/1.1
Content-Type: application/json

{
    "first_name": "Mark",
    "last_name": "Zuckerber",
    "email": "mark@gmail.com",
    "password": "password"
}

###
DELETE {{baseUrl}}/6656b500c058540fb2dab9a5 HTTP/1.1
